spring.application.name=backend
spring.config.import=optional:file:.env[.properties],optional:file:backend/.env[.properties]
spring.data.redis.repositories.enabled=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

mailtrap.api-token=${MAILTRAP_API_TOKEN}
mailtrap.api-url=${MAILTRAP_API_URL}
mailtrap.from-email=${MAILTRAP_FROM_EMAIL}
mailtrap.from-name=${MAILTRAP_FROM_NAME}

app.base-url=${APP_BASE_URL}
app.frontend-url=${APP_FRONTEND_URL}

gemini.api.key=${GEMINI_API_KEY}
